POST http://localhost:3000/api/patients/profile
Content-Type: application/json


{
   "fullName": "John Doe",
   "birthDate":"12/5/1996",
   "gender":"female/male",
   "maritalStatus": "married",
   "phoneNumber": "0234234534",
   "email": "email@example.com",
   "address": "capecoastgh"



}